### ISSUE TITLE
MQTT SSL not connecting with self signed ".pem" certificate

### ISSUE THREAD

**Issue by iHamVic** [ckrey/MQTT-Client-Framework#238]
I have been trying to connect to a local MQTT Server using SSL. Here is my connect method
```swift
var SSLCertificates: [Data] = [] 

let path = Bundle.main.path(forResource: STSSLCertificateFile, ofType: "pem") 
let certificate = try Data(contentsOf: URL(fileURLWithPath: path), options:Data.ReadingOptions.mappedIfSafe)
SSLCertificates.append(certificate)

let securityPolicy:MQTTSSLSecurityPolicy = MQTTSSLSecurityPolicy.init(pinningMode: MQTTSSLPinningMode.certificate)
securityPolicy.allowInvalidCertificates = true

self.manager.connect(to: host,
                   port: port,
                   tls: true,
                   keepalive: 10,
                   clean:true,
                   auth: true,
                   user: username,
                   pass: password,
                   will: false,
                   willTopic: nil,
                   willMsg: nil,
                   willQos: MQTTQosLevel.exactlyOnce,
                   willRetainFlag: false,
                   withClientId: clientID,
                   securityPolicy: securityPolicy,
                   certificates: SSLCertificates)
```

Host, Port, Username and password are passed correctly. SSLCertificates contains one element after reading from bundle.

Log Output:
```
MQTTSessionManager connectTo:xxx.xxx.xxx.xxx
2016-11-21 18:56:00.970 [23692:219207] [MQTTSessionLegacy] initWithClientId:56-00-68160754TzJ 
2016-11-21 18:56:00.970 [23692:219207] [MQTTSession] init
2016-11-21 18:56:00.971 [23692:219207] [MQTTSessionManager] connecting
2016-11-21 18:56:00.972 [23692:219207] MQTTSessionLegacy connectToHost:xxx.xxx.xxx.xxx port:xxxx usingSSL:1 connectHandler:0x0
2016-11-21 18:56:00.976 [23692:219207] [MQTTSession] connectWithConnectHandler:0x0
2016-11-21 18:56:00.976 [23692:219207] [MQTTSession] connecting
2016-11-21 18:56:01.008 [23692:219207] [MQTTPersistence] Persistent store: /Users/xxx/Library/Developer/CoreSimulator/Devices/63792682-755F-4055-9746-DB0781B64804/data/Containers/Data/Application/1E7250D4-6B64-4019-9626-390ECBA9A198/Documents/MQTTClient
2016-11-21 18:56:01.011 [23692:219207] [MQTTSSLSecurityPolicyTransport] open
2016-11-21 18:56:06.826 [23692:219207] [MQTTCFSocketTransport] close

[observeValue(forKeyPath:of:change:context:)] [MQTTSessionManager State: Connecting]
```
I traced the flow using breakpoints and found that in ```MQTTSSLSecurityPolicyTransport``` class ```open()``` these two conditions are executed and ```connectError``` variable is set to ```NSError```
```ObjC
if(!CFReadStreamSetProperty(readStream, kCFStreamPropertySSLSettings, (__bridge CFDictionaryRef)(sslOptions))){
            connectError = [NSError errorWithDomain:@"MQTT"
                                               code:errSSLInternal
                                           userInfo:@{NSLocalizedDescriptionKey : @"Fail to init ssl input stream!"}];
}
if(!CFWriteStreamSetProperty(writeStream, kCFStreamPropertySSLSettings, (__bridge CFDictionaryRef)(sslOptions))){
            connectError = [NSError errorWithDomain:@"MQTT"
                                               code:errSSLInternal
                                           userInfo:@{NSLocalizedDescriptionKey : @"Fail to init ssl output stream!"}]; }
``` 
Because of this ```MQTTCFSocketTransport ``` object's ```close()``` is called.

Neither MQTTs is connecting successfully nor its changing the ```state``` of ```MQTTSessionManager ```
There is also no issue in broker since we tested it with other MQTT Libraries.
Am I missing any step? Why  ```connectError```  is set to ```errSSLInternal```. Please guide me.

Xcode Version: 8.1
Testing in iPhone & iOS Simulator: iPhone (9.0)
Library installed using Pod File: ```pod 'MQTTClient'```

**Comment by iHamVic** [comment]
I couldn't fix the issue but found a work around.

Step 1: Instead of using ```MQTTSessionManager```,  I used ```MQTTSession```.
Step 2: Convert certificate file from **".pem"** file to **".der"** format. 

**How to convert?** 

1. In terminal, Go to the directory containing certificate file.
2. Use the following command for conversion 
     ```openssl x509 -in certificateName.pem -out certificateName.der -outform DER```

Final code for creating MQTT Client is as below, 
```swift
 if manager == nil {
            manager = MQTTSession.init()

            manager.clientId = cliendID
            manager.userName = username
            manager.password = password
            manager.cleanSessionFlag = true
        
            let securityPolicy:MQTTSSLSecurityPolicy = MQTTSSLSecurityPolicy.init(pinningMode: MQTTSSLPinningMode.certificate)
            securityPolicy.allowInvalidCertificates = true
            
            let rootCertPath = Bundle.main.path(forResource:SSLCertificateFile, ofType: "der")!
            let rootCertData = NSData(contentsOfFile: rootCertPath)!
            
            manager.securityPolicy = securityPolicy
            manager.securityPolicy.pinnedCertificates = [rootCertData]
            
            manager.delegate = self
            
            manager.connect(toHost: self.host, port: port, usingSSL: true)
        }
```

**Comment by ckrey** [comment]
Sorry for my late reply, but you found the problem: You need to provide the certs to DER format

**Comment by iHamVic** [comment]
@ckrey Providing ".der" certificate file to ```MQTTSessionManager``` doesn't work. It works only when client is implemented directly using ```MQTTSession```class.
When I implemented client with ```MQTTSessionManager``` class, ```MQTTCFSocketTransport``` is called even though ```tls``` is set to true. But when the same client is implemented using ```MQTTSession``` class, ```MQTTSSLSecurityPolicyTransport``` is called. Does this mean a bug is present in ```MQTTSessionManager``` when ".der" is used? or my understanding of ```MQTTSessionManager``` is wrong. Please enlighten me.

**Comment by ckrey** [comment]
Thanks for tracking this down. I will fix the problem in `MQTTSessionManager`

**Comment by ckrey** [comment]
Works now!

**Comment by hovven** [comment]
I have same problem and still can't connect

`var session = MQTTSession()
        session?.delegate = self
       
        let userName = "username"
        let password = "pass"
        let host = "host"
        let port = "port"
        let sessionManager = MQTTSessionManager()
        
        let certificate = Bundle.main.path(forResource: "cert", ofType: "der")

        let securityPolicy = MQTTSSLSecurityPolicy.init(pinningMode: .certificate)
        
        securityPolicy?.allowInvalidCertificates = true
        
        securityPolicy?.pinnedCertificates = [NSData.init(contentsOfFile: certificate!)!]
        
        sessionManager.connect(to: host, port: port, tls: true, keepalive: 60, clean: true, auth: true, user: userName, pass: password, will: false, willTopic: nil, willMsg: nil, willQos: .atMostOnce, willRetainFlag: false, withClientId: clientId, securityPolicy: securityPolicy, certificates: [NSData.init(contentsOfFile: certificate!)!], protocolLevel: .version311, connectHandler:nil
        })`

i also should mention that [this code](https://stackoverflow.com/a/39422996) works for me but I wondered why can't make connection with MQTTClient

can anybody help me?
